djangocon/2025.djangocon.africa

.github/workflows/coverage.yml
.github/workflows/django.yml
codecov.yaml
core/settings.py

Update version of actions checkout to v4 to silence warnings.

Use actions v4

---

.env_example
.gitignore
README.md
core/settings.py
core/urls.py
package-lock.json
package.json
tailwind.config.js
website/static/src/tailwind_input.css
website/templates/website/_base.html
website/templates/website/page_home.html
website/urls.py
website/views.py

Here's what I covered:
1. TailwindCSS setup. This setup should last for a long time
2. Docs an DX: I maed the app a bit easier to run and added some README docs 
3. Made a home page: This is very basic for now. It only contains some basic details
The goal here was to make a little foundation on which others can build. I expect that the home page will change a lot.

Placeholder home page + Tailwindcss integrtation and README

---

.github/workflows/django.yml

- Changed image version from 10.8 -> 14.13
- Django environment variable fix
- pytest fix

django workflow fix

---

.github/workflows/django.yml
.github/workflows/ruff.yml

- Changed the environments to the new one for `pytest`.
- update Ruff command to use 'check' subcommand

Workflow fix

---

core/settings.py

Add 2025.djangocon.africa to allowed hosts.

Add domain to settings.py

---

core/settings_base.py
core/settings_dev.py
core/settings_prod.py
custom_auth/views.py

- ruff cleanup
- refactored db config

Ruff cleanup

---

static/src/tailwind_final.css
static/src/tailwind_input.css
tailwind.config.js
templates/_base.html
templates/page_home.html
website/header_menu_items.py

- removes broken links
- best effort implementation of designs
- includes all necessary info 
- added social links 
- still needs photos

Home page styled

---

.github/scripts/deploy.py
templates/page_home.html

- enable reloading
- minor template update for testing.

Pythonanywhere fix

---

core/settings_base.py
core/urls.py

* When DEBUG is `False`, the admin path is fetched from the env file.

refactor: change admin path when DEBUG is False

---

README.md
locale/fr/LC_MESSAGES/django.po
templates/page_coc.html
templates/page_home.html
templates/page_news_detail.html

Add translate tags to HTML file to support translations and add instructions for translations to README.md

Add translation tags to HTML files, update README.md

---

README.md
locale/fr/LC_MESSAGES/django.po
sponsors/templates/sponsors/sponsors.html
templates/page_home.html
templates/page_speaker_resources.html
templates/page_speaking.html
templates/page_sponsor_us.html
website/header_menu_items.py
website/urls.py
website/views.py

Changes in this PR
- Add Speaking page
- CFP link
- Speaker resources page
- Sponsor us page
- Sponsors link

Add speaking, speaker resources and sponsor us pages

---

templates/page_sponsor_us.html

Replace sponsor logos with link to sponsors page on sponsor us page.

Add link to sponsors on sponsor us page

---

sponsors/templates/sponsors/sponsors.html

refactor: fix the structure of the sponsors page.

---

static/src/tailwind_final.css

refactor: missing tailwind file

---

templates/partials/_header.html

- Temporarily remove (comment out) unlinked buttons.

refactor: temporarily remove unlinked buttons

---

static/src/tailwind_final.css
templates/page_opportunity_grants.html

- Added a highlighted message on the top of the Opportunity Grants page.

refactor: add a top highlighted message on og page

---

templates/partials/_mobile_nav.html
website/header_menu_items.py

- Fix the order of the navbar menu items.

refactor: Nav bar rearrange

---

core/settings_base.py
core/settings_dev.py
templates/_base.html
templates/page_tickets.html
templates/partials/_header.html
website/urls.py
website/views.py

Added the ticket system from UZA

feat: add ticket purchase page and integrate UZA API for ticketing

---

.github/scripts/deploy.py

- Step added to activate the venv

refactor: add activate venv step

---

website/constants.py
website/views.py

- moved Schedules list to `constants`
- corrected schedule date

refactor: move Schedules list to constant and corrected schedule date

---

templates/page_home.html
website/urls.py
website/views.py

- Fixed wrong "Learn more" link for sponsors
- Fixed broken sponsor us link

refactor: Fix broken links

---

locale/fr/LC_MESSAGES/django.po

Here is the initial French translation. Some sections were added after the translation work began and are still untranslated, we'll address those as soon as possible.
Kudos to @Arya-AD and @anjaniacatus

feat: initial fr translation

---

locale/fr/LC_MESSAGES/django.po
templates/page_home.html
website/constants.py

- add forgotten translation on schedules
- updated translation
- add `translate` in schedules table template

refactor: add leftover translation

---

templates/page_tickets.html

- Fixed wrong button color on Tickets page
- Added underline on ticket email link

refactor: fix button on tickets page

---

website/constants.py

refactor: change cfp notification date

---

website/header_menu_items.py

- Display organizers link to nav bar

refactor: display organizers link
